/* AUTO-GENERATED from "LHS Club Directory.dc.html" — regenerate after any club edit. */
(function () {
  const CATS = [
    ['stem', 'STEM & Engineering', 250],
    ['cte', 'Career & Technical', 205],
    ['health', 'Health & Medicine', 162],
    ['biz', 'Business & Finance', 132],
    ['arts', 'Arts, Music & Writing', 62],
    ['honor', 'Honor Societies', 38],
    ['teams', 'Academic Competition Teams', 22],
    ['culture', 'Culture, Language & Affinity Groups', 350],
    ['service', 'Service & Advocacy', 322],
    ['faith', 'Faith & Wellness', 292],
    ['hobby', 'Games & Hobbies', 268],
    ['sports', 'Sports & Performance', 96]
  ];
  const CLUBS = [
    ['Academic Team', 'Ms. Deady & Mr. Crisp', 'A', 'teams', `Preparing to compete in academic team and scholastic bowl tournaments.`],
    ['Anna Sudha Club', 'Ms. Malik', 'T', 'service', `Meaningful opportunities to combat food insecurity, reduce food waste, and serve the community through hands-on service projects, leadership development, and partnerships with local organizations — making a lasting impact at Lightridge and in the broader community.`],
    ['Arduino Club', 'Mr. Archie', 'X', 'stem', `Students excited to learn electronics, circuitry, programming, and robotics. Members work with the Arduino platform on hands-on projects, starting with simple circuits and progressing to programming small robots and other interactive devices.`],
    ['Aviation Club', 'Mr. Elwood', 'T', 'cte', `Focused on atmospheric flight topics (not rocketry), flight simulator operations, and wind tunnel testing.`],
    ['Baseball Club', 'Mr. Moreland', 'T', 'sports', `For the baseball team and its fans.`],
    ['Biomedicine Club', 'Ms. Averion & Mr. Akers', 'L', 'health', `Support for students pursuing careers in medicine and biology-related sciences: essay help, internship lists, volunteer connections, and competition preparation.`],
    ['Black Student Union', 'Ms. Schrader', 'T', 'culture', `Bringing students together for connection and conversation — building community through special events, volunteerism, and opportunity.`],
    ['Boys Leading Boys', 'Mr. Alcazar', 'T', 'faith', `A men's mental health club focused on healthy, productive discussion about what it means to be a boy or man in today's world.`],
    ['Bolt TV', 'Ms. Barbrow', 'TL', 'arts', `Bolt TV is the visual source of Lightridge weekly info — the daily announcements plus Bolt TV Entertainment.`],
    ['Chess Club', 'Mr. Wainwright', 'T', 'hobby', `Practice and improve your chess game with other players.`],
    ['Computer Science Honor Society', 'Mr. Archie', 'B', 'stem', `For students who enjoy coding and computer science and want to use those skills to help others. Members take part in coding activities and competitions while running outreach that helps younger students learn programming.`],
    ['Creative Writing', 'Mr. Ayers', 'T', 'arts', `Opportunities for members to write and be creative together.`],
    ['Dance Team', 'Ms. Boss', 'T', 'sports', `Pom, hip hop, and jazz routines performed at basketball halftimes, pep rallies, and other school-sponsored events.`],
    ['Data Science Research Society', 'Mr. Cramer', 'T', 'stem', `Explore where data science meets other fields. Members take on small data science projects, write articles about their interests in the field, and collaborate with peers to present ideas to the club.`],
    ['DECA', 'Ms. Koerner, Mr. Huynh, Mr. Beyer & Ms. Musa', 'T', 'cte', `Co-curricular marketing club preparing students for careers in marketing, finance, hospitality, and management.`],
    ['Doctors Without Borders — Friends of MSF', 'Ms. Bock', 'T', 'service', `Raising awareness about global health challenges and illnesses. Goals: run awareness campaigns, debate different illnesses and disorders, and promote volunteer opportunities.`],
    ['Engineering Club', 'Ms. Choudhari', 'L', 'stem', `Mentoring FIRST Tech Challenge teams and competing in the Toshiba/NSTA ExploraVision research paper competition. Toward the end of the year the club focuses on STEM volunteering.`],
    ['Esports', 'Mr. Zawistowski', 'T', 'sports', `Competitive video gaming against other schools.`],
    ['FBLA', 'Ms. Cooley', 'L', 'cte', `Lightridge's chapter of the largest student business organization in the world. Members develop leadership skills, explore careers in business and technology, and make an impact in the school and community.`],
    ['Fellowship of Christian Athletes', 'Ms. Yagel', 'L', 'faith', `A space for athletes to talk about Jesus and take part in games and sport activities.`],
    ['Finance and Investments Club', 'Mr. Beyer', 'L', 'biz', `Members pool knowledge, practice stock market simulations, and combine funds to learn about wealth-building, market analysis, and financial careers.`],
    ['French Club', 'Ms. Botros', 'T', 'culture', `Spreading French culture and promoting the French language throughout the school.`],
    ['Friendship Club', 'Ms. McLemore & Ms. Borg', 'L', 'culture', `We make friendships, stay inclusive to all, and celebrate who we are while respecting each other. We aim to break down barriers, challenge stereotypes, and encourage acceptance of the LGBTQ+ community.`],
    ['FCCLA', 'Ms. Zaremski & Ms. Gore', 'T', 'cte', `Future Career and Community Leaders of America — the Family and Consumer Sciences CTSO. Our main focus is food-related community service.`],
    ['FFA', 'Ms. Zaremski & Ms. Gore', 'L', 'cte', `Future Farmers of America. Our main focus is the courtyard garden, with plant and flower sales to support it, plus giving back to the community.`],
    ['Geology Club', 'Mr. Knappenberger', 'L', 'hobby', `Discover the secrets of the Earth — rocks, minerals, fossils, and the forces that shape our planet.`],
    ['German Club', 'Ms. Deady', 'T', 'culture', `Activities that let students learn about the German language, culture, and traditions.`],
    ['Girls in STEM', 'Ms. Goins', 'T', 'stem', `Experiential learning and volunteering opportunities that promote STEM education. Through hands-on activities, events, mentorship, and outreach, members explore STEM, build confidence, and develop leadership skills.`],
    ['Gosh Yarn In (Crochet Club)', 'Ms. Henry', 'L', 'hobby', `Crocheting items to donate, and teaching others how to crochet.`],
    ['Green Team (Environmental Club)', 'Ms. Buskey, Ms. Buttery & Mr. Chi', 'T', 'service', `A group of students and staff who work together to protect nature and promote sustainable habits. We raise awareness about issues like climate change and conservation through hands-on projects and community building events, and highlight lesser-known environmental issues and small ways people can make an impact.`],
    ['Guitar Club', 'Mr. White & Mr. Greentree', 'L', 'arts', `Students gather, teach each other guitar, and prepare for in-school performances at events like the Wellness Expo.`],
    ['HAPI Club', 'Ms. Moulton', 'L', 'culture', `Promoting cultural connection and camaraderie.`],
    ['Hispanic/Latino Association (HLA)', 'Ms. Selvaraj, Sr. Montoya & Sra. Bentacur', 'T', 'culture', `Open to all students, HLA celebrates and supports our Latin American students. We take part in cultural events through the year, celebrate together with fiestas, and join community service projects.`],
    ['HOSA — Future Health Professionals', 'Ms. Knode', 'L', 'health', `A student-led career and technical organization for students pursuing medical and healthcare fields. Our focus is the Virginia HOSA State Leadership Conference; top-three finishers advance to the International Leadership Conference.`],
    ['Invest in Girls & Investment Club', 'Mr. Kim', 'L', 'biz', `Economics and investing tend to be dominated by boys. This club works to increase interest in economics, investing, and personal finance among girls — learning investing fundamentals, how financial markets work, and applying that understanding in live competitions sponsored by the Council for Economic Education.`],
    ['Jewelry & Bracelet Making', 'Ms. Brenan', 'L', 'hobby', `Making jewelry — mostly bracelets — and learning new techniques together.`],
    ['Key Club', 'Ms. Herbstritt & Ms. Barbrow', 'B', 'service', `Key Club International empowers high school students to become leaders through service to others. This student-led organization offers members opportunities to serve, build character, and develop leadership.`],
    ['Latin Club', 'Mr. Boscovitch', 'T', 'culture', `For Latin students exploring Roman culture and history beyond the classroom. We celebrate Roman-themed events, prepare for state convention, and organize service projects.`],
    ['LHS Agni', 'Mr. Boscovitch', 'L', 'culture', `Lightridge's official South Asian dance team. We perform at pep rallies and multicultural fairs and host events and fundraisers around the county to share and build appreciation for South Asian culture through music and dance.`],
    ['Literary Magazine', 'Ms. Ehring & Ms. Cleary', 'T', 'arts', `The club publishes Thoughts of Thunder, our annual magazine featuring Lightridge student writing, visual art, and music.`],
    ['Makerspace', 'Mr. Archie', 'X', 'hobby', `An open, creative space to explore interests, learn new skills, and make projects. Members have access to a wide variety of tools and materials, from knitting, sewing, and fused beads to 3D printing, Arduino electronics, and wood and metal fabrication.`],
    ['Medical Research Society', 'Mr. Maycott', 'L', 'health', `Introducing research skills to students — particularly freshmen and sophomores — with a focus on medical topics, aiming to inform the local community inside and outside Lightridge.`],
    ['MEDLIFE', 'Ms. Lahiri', 'L', 'health', `Promoting health awareness, community service, and access to healthcare. We educate students about global and local health issues, organize service and fundraising activities, and encourage students to help improve the health and well-being of others.`],
    ['Mission Mail', 'Ms. da Silva', 'L', 'service', `Club details TBD — contact the sponsor for more information.`],
    ['Mock Trial Team', 'Ms. Safran & Ms. Bria', 'B', 'teams', `We examine criminal and civil cases and compete against other schools as either the defense or the prosecution.`],
    ['Model UN', 'Ms. Safran', 'A', 'teams', `Students learn about global diplomacy and compete in Model UN competitions.`],
    ["Morgan's Message", 'Ms. Zawistowski', 'T', 'faith', `Spreading awareness of mental health, especially among athletes and the unique pressures they feel as part of their sport.`],
    ['Mu Alpha Theta (Math Honor Society)', 'Ms. Averion & Ms. Henry', 'T', 'honor', `Math excellence and peer empowerment: tutoring, national assessments, and friendly competitions with Champe and Freedom.`],
    ['Music Composition Association', 'Mr. Cutshaw & Mr. Donohue', 'T', 'arts', `MCA is about making music. We teach, talk about, and give feedback on compositions.`],
    ['Muslim Students Association', 'Ms. Malik', 'L', 'faith', `Building an inclusive faith-based community, providing a space for Muslim students to practice their traditions, and fostering cross-cultural understanding through school-wide and regional events.`],
    ['National Alliance on Mental Illness (NAMI)', 'Ms. Ramos', 'T', 'health', `NAMI promotes awareness and reduces stigma around mental illness. Meetings include lessons and volunteer events focused on mental health awareness — NAMI walks, fundraising for mental health hospitals, and creating goodie bags for mental health institutes.`],
    ['National Art Honor Society', 'Mr. Haller', 'L', 'honor', `Honor society for dedicated art students. We organize fundraisers, host art exhibits, and create public art and murals for the school.`],
    ['National English Honor Society', 'Ms. Cichoski, Ms. Lombardo & Mr. Alcazar', 'L', 'honor', `Members work with others who are passionate about literature and writing. We host events through the year for volunteer experience and to help others realize the power of English — a chance to grow as a writer and add something unique to your resume.`],
    ['National Honor Society', 'Ms. Herbstritt', 'B', 'honor', `NHS equips students with the knowledge and skills to be transformative leaders in school, community, and beyond, and provides a bridge between students and school leaders.`],
    ['National Society of Black Engineers', 'Mr. Archie', 'L', 'stem', `NSBE supports students interested in engineering and related STEM careers — exploring engineering fields, preparing for college and future careers, connecting with internships, and building a supportive community of future engineers.`],
    ['Nuclear Club', 'Mr. Montoya', 'L', 'stem', `The study of atomic science: preparing for competitions, fostering research opportunities, and holding lessons on nuclear physics and engineering.`],
    ['Origami for Good', 'Ms. Trickett', 'T', 'service', `We use the Japanese art of paper folding to spread joy, combat loneliness, and support communities.`],
    ['Philosophy Club', 'Dr. Legnini', 'T', 'hobby', `We discuss big ideas.`],
    ['Picture Pals', 'Ms. Ehring', 'L', 'service', `Fostering growing literacy in elementary-aged students by hosting writing and publishing workshops in the Aldie community.`],
    ['Pokémon Club', 'Mr. Morano', 'T', 'hobby', `Play Pokémon cards together.`],
    ['Quill & Scroll Journalism Honor Society', 'Ms. Moulton', 'B', 'honor', `Acknowledges and elevates journalism-related work and leadership. Before-school meetings only.`],
    ['RC Car Club', 'Mr. Paine', 'L', 'stem', `We build and race RC cars through the year — and we're building an RC car track this year.`],
    ['RC Planes', 'Mr. Bosse', 'L', 'stem', `We build and fly RC planes.`],
    ['Robotics at Lightridge', 'Mr. Archie', 'A', 'stem', `Three teams compete in FIRST Tech Challenge. From September through February, students design, build, program, test, and drive a robot for the season's challenge, using CAD, fabrication, CNC machining, programming, and problem-solving.`],
    ['Rocketry', 'Mr. Archie', 'T', 'stem', `A nationally recognized competitive club for students interested in how rockets are designed, built, tested, and flown. Now in its third year, the club gives hands-on rocketry experience while preparing for competitions across Northern Virginia.`],
    ['Science National Honor Society', 'Ms. Min', 'L', 'honor', `Recognizing academic excellence in science, encouraging student-led research, and promoting community outreach and peer tutoring in STEM at local middle and elementary schools.`],
    ['Sociedad Honoraria Hispánica', 'Ms. Fermoselle & Ms. Montecalvo', 'T', 'honor', `For students who passed Spanish 1–4 with As and Bs and continue through level V and/or AP. Members do community service celebrating the Spanish language and Spanish-speaking cultures, and tutor levels 1–3.`],
    ['Society of Women Engineers', 'Ms. Choudhari', 'T', 'stem', `For high school girls interested in the many aspects of engineering, with a focus on empowering elementary-school girls to keep pursuing science goals.`],
    ['Sources of Strength', 'Ms. Kenworthy', 'L', 'faith', `A best-practice, strength-based, upstream suicide prevention and mental health promotion program.`],
    ['South Asian Student Association (SASA)', 'Ms. Choudhari & Ms. Rajakumar', 'L', 'culture', `An inclusive, welcoming environment where students connect, make friends, and learn about South Asian culture, history, and traditions. We host social events and community service projects to promote cultural awareness.`],
    ['Spanish Club', 'Ms. Pfaff', 'L', 'culture', `For students with an interest in and appreciation for the Spanish language and Hispanic cultures. We celebrate holidays from around the Spanish-speaking world, learn about customs and popular media, and take field trips.`],
    ['Speech and Debate Team', 'Ms. Safran & Ms. Bass', 'A', 'teams', `Students compete in Lincoln-Douglas debate, Congressional debate, or speech events.`],
    ['Tabletop Gaming Club', 'Mr. White', 'T', 'hobby', `A place to talk about tabletop games — Dungeons & Dragons, Magic, and board games like Ticket to Ride — and, time permitting, play them.`],
    ['Technology Student Association (TSA)', 'Ms. Khodayar', 'L', 'cte', `A national non-profit career and technical student organization for middle and high school students engaged in science, technology, engineering, and mathematics.`],
    ['The Cyber Challenge Club', 'Ms. Iman-Brantley', 'T', 'cte', `Preparing students for cybersecurity competitions through hands-on training, teamwork, problem-solving, and real-world cyber defense challenges — CyberPatriot, NCL, and Capture the Flag events.`],
    ['Unified Sports', 'Ms. Selvaraj, Mr. Re & Ms. Boss', 'L', 'sports', `Open to all students regardless of ability or prior sports experience. We include every team member and help each other while playing various sports.`],
    ['Unified STEM', 'Ms. Bass', 'T', 'stem', `Extending STEM experiences and opportunities to students identified with an exceptionality.`],
    ['United Against Hunger', 'Ms. Snider-Rosinski', 'L', 'service', `Finding ways to alleviate hunger.`],
    ['Wharton Investment Competition', 'Mr. Kim', 'T', 'biz', `The Wharton School sponsors a worldwide high school investment competition where teams develop an investment plan and strategy based on a client's goals and values.`],
    ["Women's Literature Club", 'Ms. Cleary & Ms. Watson', 'T', 'arts', `We read books written by, for, and about women, discussing literature of merit and fundraising to help female-focused local organizations. We craft and snack while we meet.`],
    ['World Citizens Club', 'Ms. Lahiri', 'T', 'service', `Advocating for immigrant families and creating awareness of the many cultures represented in our area.`],
    ['The Book Was Better', 'Ms. Ivory & Ms. Lombardo', 'B', 'arts', `We love books and we love people who love books. We read books, chat about books, and have fun doing it.`]
  ];
  window.LHS_CATS = CATS;
  window.LHS_CLUBS = CLUBS;
})();
